name: lint
on:
  - push
  - workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v3
      - name: run pylint
        shell: bash
        run: |
          set -e
          pip install pylint requests xmltodict
          pylint paloalto-*.check


